# Generated by Django 3.1.7 on 2021-02-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.school')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.teacher')),
            ],
        ),
    ]
