# Generated by Django 3.1.7 on 2021-02-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0003_school_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Teacher_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.student')),
                ('school_teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.school_teacher')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.subject')),
            ],
        ),
    ]
