# Generated by Django 3.1.7 on 2021-02-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0004_student_teacher_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Teacher_Subject',
        ),
    ]
