# Generated by Django 3.1.7 on 2021-02-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0005_delete_student_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_School_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.student')),
                ('school_teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.school_teacher')),
            ],
        ),
    ]
