# Generated by Django 3.1.7 on 2021-02-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0007_student_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_school_teacher',
            old_name='school_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='student_subject',
            old_name='school_name',
            new_name='student_name',
        ),
    ]
